# Generated by Django 4.1.5 on 2023-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('roll_number', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
