# Generated by Django 4.1.4 on 2023-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.IntegerField(max_length=225),
        ),
    ]
